POST http://localhost:3000/signin
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
    "email":"a@b.com",
    "password":"password"
}

###

POST http://localhost:3000/signup
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
    "email":"a@b.com",
    "password":"password"
}

###
